
##
# Spring Cloud AWS
# https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/appendix.html
##
cloud:
    aws:
        stack:
            auto: false
            enabled: false
        credentials:
            access-key: localstackAccessKeyId
            secret-key: localstackSecretAccessKey
        region:
            static: sa-east-1
        sqs:
            endpoint: http://localhost:4566
            listener:
                auto-startup: true
                fail-on-missing-queue: false
                default-deletion-policy: NO_REDRIVE
                max-number-of-messages: 10
                visibility-timeout: 30  # 30s
                wait-timeout: 20        # 20s
                back-off-time: 10000    # 10s

logging:
    level:
        io:
            awspring:
                cloud:
                    messaging:
                        core: info
                        listener: info
        com:
            amazonaws:
                services:
                    sqs: debug

# Samples configuration
samples.aws.sqs.producer-queue: newProductsQueue
samples.aws.sqs.consumer-queue: customersCreatedQueue